/** Main catalog: industries we serve (listing + detail routing). */
export const industriesCatalog = [
  {
    id: 1,
    name: "Law & Legal",
    slug: "law-legal",
    pageTitle: "Law Firm Web Design & SEO for Solicitors",
    keywords: ["Legal web design", "law firm marketing", "SEO for attorneys"],
    teaser: "Authority-driven websites, structured service pages, and search visibility for firms competing on trust.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=80",
    cluster: "regulated",
  },
  {
    id: 2,
    name: "Finance & Fintech",
    slug: "finance-fintech",
    pageTitle: "Web Development for Finance & Fintech Firms",
    keywords: ["Fintech UI/UX", "wealth management websites", "banking web design"],
    teaser: "Crisp product narratives, secure UX patterns, and dashboards that feel as serious as your compliance stack.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=80",
    cluster: "regulated",
  },
  {
    id: 3,
    name: "Management Consulting",
    slug: "management-consulting",
    pageTitle: "Corporate Web Design for Business Consultants",
    keywords: ["B2B consulting websites", "professional services branding"],
    teaser: "Editorial layouts, case-forward storytelling, and positioning sites for high-trust advisory brands.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
    cluster: "professional",
  },
  {
    id: 4,
    name: "Insurance",
    slug: "insurance",
    pageTitle: "Website Design for Insurance Brokers & Agencies",
    keywords: ["Insurance lead gen", "broker websites", "insurance portal design"],
    teaser: "Quote flows, partner portals, and lead capture tuned for long-cycle consideration.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80",
    cluster: "regulated",
  },
  {
    id: 5,
    name: "Real Estate",
    slug: "real-estate",
    pageTitle: "Luxury Real Estate Web Design & Property Portals",
    keywords: ["Property listing websites", "real estate SEO", "broker web design"],
    teaser: "Immersive listings, map-led discovery, and SEO for markets where visuals close the deal.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    cluster: "built",
  },
  {
    id: 6,
    name: "Construction",
    slug: "construction",
    pageTitle: "Web Design for Construction & MEP Companies",
    keywords: ["Civil engineering websites", "contractor SEO", "construction branding"],
    teaser: "Capability pages, project galleries, and tender-friendly credibility for technical buyers.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80",
    cluster: "built",
  },
  {
    id: 7,
    name: "Architecture",
    slug: "architecture",
    pageTitle: "Portfolio Design for Architects & Designers",
    keywords: ["Architecture firm websites", "3D render portfolios", "design SEO"],
    teaser: "Portfolio systems that prioritize imagery, process, and awards without sacrificing performance.",
    image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&q=80",
    cluster: "creative",
  },
  {
    id: 8,
    name: "Interior Design",
    slug: "interior-design",
    pageTitle: "High-End Web Design for Interior Designers",
    keywords: ["Interior design branding", "luxury home design websites"],
    teaser: "Mood-led layouts, lookbooks, and inquiry paths built for high-ticket residential work.",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    cluster: "creative",
  },
  {
    id: 9,
    name: "Life Sciences",
    slug: "life-sciences",
    pageTitle: "Web Design for Biotech & Life Science Labs",
    keywords: ["Biotech website development", "science park SEO", "lab tech sites"],
    teaser: "Clear science storytelling, investor-ready pages, and structures that scale with pipeline news.",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=1200&q=80",
    cluster: "knowledge",
  },
  {
    id: 10,
    name: "Education & EdTech",
    slug: "education-edtech",
    pageTitle: "Website Design for Private Schools & EdTech",
    keywords: ["Academic web design", "e-learning platforms", "school SEO"],
    teaser: "Enrollment journeys, LMS bridges, and content systems that parents and students actually use.",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&q=80",
    cluster: "knowledge",
  },
  {
    id: 11,
    name: "Software & SaaS",
    slug: "software-saas",
    pageTitle: "SaaS Website Design & App Landing Pages",
    keywords: ["Software product sites", "SaaS UI/UX", "conversion-focused design"],
    teaser: "Positioning, pricing, and product storytelling engineered for trials and demos.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
    cluster: "knowledge",
  },
  {
    id: 12,
    name: "Renewable Energy",
    slug: "renewable-energy",
    pageTitle: "Web Design for Solar & Renewable Energy Firms",
    keywords: ["Green tech websites", "solar panel SEO", "sustainability branding"],
    teaser: "Impact metrics, installer journeys, and local SEO for markets that move fast.",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80",
    cluster: "built",
  },
  {
    id: 13,
    name: "Healthcare/Clinics",
    slug: "healthcare-clinics",
    pageTitle: "Medical Web Design for Private Clinics & Doctors",
    keywords: ["Clinic SEO", "patient booking systems", "healthcare marketing"],
    teaser: "Accessible UX, booking integrations, and compliant content for patient-first clinics.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80",
    cluster: "wellness",
  },
  {
    id: 14,
    name: "Hospitality/Hotels",
    slug: "hospitality-hotels",
    pageTitle: "Hotel Web Design & Direct Booking Solutions",
    keywords: ["Luxury hotel websites", "resort web design", "booking engine SEO"],
    teaser: "Brand-led booking paths, rich media, and SEO that protects margin on direct reservations.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80",
    cluster: "wellness",
  },
  {
    id: 15,
    name: "Fitness & Wellness",
    slug: "fitness-wellness",
    pageTitle: "Web Design for Gyms, Yoga & Fitness Centers",
    keywords: ["Fitness branding", "personal trainer websites", "wellness SEO"],
    teaser: "Membership funnels, schedules, and motivational brand systems that convert foot traffic.",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80",
    cluster: "wellness",
  },
  {
    id: 16,
    name: "Beauty & Salons",
    slug: "beauty-salons",
    pageTitle: "Website Design for Salons, Spas & Aesthetics",
    keywords: ["Salon booking websites", "spa SEO", "aesthetics clinic marketing"],
    teaser: "Service menus, booking UX, and local search for high-repeat clientele.",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80",
    cluster: "wellness",
  },
  {
    id: 17,
    name: "Life Coaching",
    slug: "life-coaching",
    pageTitle: "Conversion-Focused Web Design for Coaches",
    keywords: ["Coaching websites", "motivational speaker SEO", "lead-gen for coaches"],
    teaser: "Story-driven landing pages, webinar flows, and CRM-ready lead capture.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    cluster: "professional",
  },
  {
    id: 18,
    name: "Logistics & Shipping",
    slug: "logistics-shipping",
    pageTitle: "Web Design for Logistics & Freight Forwarders",
    keywords: ["Supply chain websites", "shipping SEO", "logistics branding"],
    teaser: "Operations credibility, tracking touchpoints, and SEO for high-intent B2B searches.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=80",
    cluster: "operations",
  },
  {
    id: 19,
    name: "Manufacturing",
    slug: "manufacturing",
    pageTitle: "Website Design for Manufacturing & Industrial",
    keywords: ["Industrial web design", "factory SEO", "B2B manufacturing sites"],
    teaser: "Spec sheets, distributor portals, and technical SEO for long sales cycles.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&q=80",
    cluster: "operations",
  },
  {
    id: 20,
    name: "E-commerce/Retail",
    slug: "ecommerce-retail",
    pageTitle: "E-commerce Web Design for Luxury Brands",
    keywords: ["Shopify experts", "online store development", "retail SEO"],
    teaser: "Premium merchandising, performance storefronts, and retention-ready journeys.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
    cluster: "operations",
  },
];

export const industryClusters = [
  { id: "regulated", label: "Regulated & advisory" },
  { id: "professional", label: "Professional services" },
  { id: "built", label: "Built environment" },
  { id: "creative", label: "Design & spatial" },
  { id: "knowledge", label: "Knowledge & technology" },
  { id: "wellness", label: "Wellness & hospitality" },
  { id: "operations", label: "Operations & commerce" },
];

export function getIndustryBySlug(slug) {
  return industriesCatalog.find((item) => item.slug === slug) || null;
}

export function getAllIndustrySlugs() {
  return industriesCatalog.map((item) => item.slug);
}
